-- MySQL Script generated by MySQL Workbench
-- Mon Sep 13 09:10:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema GeomShape
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `GeomShape` ;

-- -----------------------------------------------------
-- Schema GeomShape
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `GeomShape` DEFAULT CHARACTER SET utf8 ;
USE `GeomShape` ;

-- -----------------------------------------------------
-- Table `GeomShape`.`Drawing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeomShape`.`Drawing` ;

CREATE TABLE IF NOT EXISTS `GeomShape`.`Drawing` (
    `Id` CHAR(36) NOT NULL,
    `Name` VARCHAR(45) NULL,
    `Description` VARCHAR(45) NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeomShape`.`Shape`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeomShape`.`Shape` ;

CREATE TABLE IF NOT EXISTS `GeomShape`.`Shape` (
    `Id` CHAR(36) NOT NULL,
    `DrawingId` CHAR(36) NOT NULL,
    `OffsetX` DOUBLE NOT NULL,
    `OffsetY` DOUBLE NOT NULL,
    UNIQUE INDEX `DrawingId_UNIQUE` (`DrawingId` ASC) VISIBLE,
    PRIMARY KEY (`Id`),
    CONSTRAINT `fk_Shape_Drawing`
    FOREIGN KEY (`DrawingId`)
    REFERENCES `GeomShape`.`Drawing` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeomShape`.`Triangle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeomShape`.`Triangle` ;

CREATE TABLE IF NOT EXISTS `GeomShape`.`Triangle` (
    `Id` CHAR(36) NULL,
    `LengthA` FLOAT NOT NULL,
    `LengthB` FLOAT NOT NULL,
    `LengthC` FLOAT NOT NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeomShape`.`Circle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeomShape`.`Circle` ;

CREATE TABLE IF NOT EXISTS `GeomShape`.`Circle` (
    `Id` CHAR(36) NULL,
    `Radius` FLOAT NOT NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `GeomShape`.`Rectangle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `GeomShape`.`Rectangle` ;

CREATE TABLE IF NOT EXISTS `GeomShape`.`Rectangle` (
    `Id` CHAR(36) NULL,
    `LengthA` FLOAT NOT NULL,
    `LengthB` FLOAT NOT NULL,
    PRIMARY KEY (`Id`))
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
